# Generated by Django 6.0.3 on 2026-03-16 19:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kids Learning Workbook', max_length=200)),
                ('pdf_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/md-helal-uddin/Desktop/book/backend/protected_media'), upload_to='books/')),
                ('price_inr', models.DecimalField(decimal_places=2, default=299.0, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, default=3.99, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
