# Generated by Django 6.0.3 on 2026-03-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paypal_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_session_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=299.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
