# Generated by Django 6.0.3 on 2026-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp_inr',
            field=models.DecimalField(decimal_places=2, default=1999.0, max_digits=10),
        ),
    ]
