# Generated by Django 6.0.3 on 2026-03-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_mrp_inr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mrp_inr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_inr',
        ),
        migrations.AddField(
            model_name='product',
            name='mrp_usd',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=3.99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
