# Generated by Django 6.0.3 on 2026-03-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_mrp_inr_remove_product_price_inr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='500+ pages of logic activities for ages 3-8.'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='https://crevvo.com/wp-content/uploads/2024/02/14000-Kids-Worksheets.webp'),
        ),
    ]
