# Generated by Django 6.0.3 on 2026-03-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_description_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
