# Generated by Django 6.0.3 on 2026-03-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
