# Generated by Django 6.0.3 on 2026-03-26 05:42

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(storage=shop.models.get_protected_storage, upload_to='books/'),
        ),
    ]
